spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/second_hand
    username: root
    password: your_password
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      # 关闭静态资源的默认映射（防止干扰我们的异常捕获）
      add-mappings: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted   # 全局逻辑删除字段名
      logic-delete-value: 1         # 已删除的值
      logic-not-delete-value: 0     # 未删除的值
